name: starter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/personalinfo.png
    - assets/logofull.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png
    - assets/kamala.png
    - assets/promos.png
    - assets/Technology.png
    - assets/Business.png
    - assets/Entertainment.png
    - assets/Default.png
    - assets/Construction.png
    - assets/Education.png
    - assets/Health.png
    - assets/Housework.png
    - assets/Food.png
    - assets/Transport.png
    - .env

  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          style: normal
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          style: normal
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        
